title_prefix: UX pour développeurs

domain: ux-lois.github.io/
baseurl: /
url: https://ux-lois.github.io

github_cards: https://github.com/jlguenego/ux-static-site/edit/master/docs/_cards

collections:
  cards:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "cards"
    values:
      image: "default"
      color: gray
      layout: "card-details"
